def text_to_bits(text, encoding='utf-8', errors='surrogatepass'):
    # Thanks jfs - convert-binary-to-ascii-and-vice-versa
    bits = bin(int.from_bytes(text.encode(encoding, errors), 'big'))[2:]
    return bits.zfill(8 * ((len(bits) + 7) // 8))


def text_from_bits(bits, encoding='utf-8', errors='ignore'):
    # Thanks jfs - convert-binary-to-ascii-and-vice-versa
    n = int(bits, 2)
    return n.to_bytes(
        (n.bit_length() + 7) // 8, 'big').decode(encoding, errors) or '\0'


def LFSR(text_bin, key, poly, lfsr):
    # The lfsr is generated by the key and polynomial
    for digit in text_bin:
        xor = sum(key[num] for num in poly)
        xor = 0 if xor % 2 == 0 else 1
        lfsr.append(xor)
        key.insert(0, xor)
        del key[-1]
    return lfsr


def FullAdder(text_bin, lfsr_17, lfsr_25, cin, crypt_bin):
    # This is the standard full-adder truth table
    for i, digit in enumerate(text_bin):
        lsfr_cin_sum = lfsr_17[i] + lfsr_25[i] + cin
        s = 0 if lsfr_cin_sum == 0 or lsfr_cin_sum == 2 else 1
        cout = 0 if lsfr_cin_sum == 0 or lsfr_cin_sum == 1 else 1
        crypt_bin.append((s + digit) % 2)
        cin = cout
    return crypt_bin


### Plaintext
plaintext = (
    "One of Landover's platinum tithers recently expressed a "
    "concern I've heard frequently of late: 'Brother Harry, "
    "given all the people who say they've accepted Christ, will "
    "Heaven be overcrowded?'  The answer, friends, is absolutely not."
    "  Granted, we have no idea how large Heaven actually is, "
    "but it doesn't matter, because there will be far fewer people in "
    "Heaven than you might think.  In fact, the vast majority of people"
    " you know will roast in Hell instead.  We know the first plunged "
    "into the smelly, hot bowels of Satan's abode will be the members"
    " of the liberal cult.  A cult is a group of individuals who "
    "share a common, outlandish belief they are not willing to "
    "subject to rational discourse.  I am, of course, referring to "
    "those sacrilegious, blasphemous liberals who think the Bible "
    "is a tiny pamphlet containing nothing more than the verse, "
    "John 3:16.  The liberal cultists say what you do wrong doesn't "
    "make one iota of difference – as long as you say, 'I accept Jesus,' "
    "you're going to Heaven.  Can you believe that?  According "
    "to this cult, once you say, 'I accept Jesus,' you can murder, "
    "rape, rob, plunger, pillage, blow up churches and molest babies,"
    " and you're still going to Heaven as though nothing happened, "
    "just 'cause you uttered the magic words.  Needless to say, "
    "the liberal cultists won't debate you on this, because they "
    "know it makes no sense, hence making them cultists.  But "
    "they have to hold this belief, because they know it's the "
    "only hope they have to go to Heaven despite their depraved, "
    "decadent, deviant, debauched, degenerate lifestyles.  True "
    "Christians know that the Bible, Old and New Testaments "
    "combined, promises Hell for countless sinners.  And "
    "when you review the Bible in context, just about everyone "
    "is going to Hell.  Through the apostle, Paul, Jesus told "
    "us the majority of so-called Christians cannot enter "
    "Heaven because of their sins (and if you don't go to "
    "Heaven, the only place left is Hell).  'Know ye not that "
    "the unrighteous shall not inherit the kingdom of God?  "
    "Be not deceived: neither fornicators, nor idolaters, nor "
    "adulterers, nor effeminate, nor abusers of themselves with "
    "mankind, Nor thieves, nor covetous, nor drunkards, nor "
    "revilers, nor extortioners, shall inherit the kingdom of God "
    "(1 Corinthians 6:9-10).'  I don't know where the liberal "
    "cultists get off suggesting otherwise.  I haven't read "
    "any verse saying John trumps Paul.  Just because John's "
    "verse appears on more banners at college football games "
    "doesn't make it preeminent.  And under the long accepted"
    " legal doctrine that the specific controls over the general,"
    " Paul's pronouncement that these particular people are going to "
    "Hell is clearly an exception to the general rule vaguely "
    "enunciated by John.  When you consider Paul's words with the "
    "rest of the Bible, rest assured, there'll be plenty of room "
    "for driving ranges in Heaven.  Studies show the majority of "
    "people have had premarital sex.  They're condemned as "
    "fornicators.  All those other than Christians are going "
    "to Hell as idolaters (and that includes the Catholics who "
    "worship that harlot, Mary, and the so-called 'saints').  Studies"
    " show most people get drunk at times, so they're out.  And, of"
    " course, the sodomites are out (but we knew that anyway, without "
    "Paul's words).  But the Hell-bound group is even larger.  "
    "Of the few people remaining, most of them will go to Hell "
    "as adulterers.  Matthew told us that anyone who lusts after "
    "(has sexual thoughts about) someone to whom he is not "
    "married is an adulterer (Matthew 5:28).  Matthew also told us that "
    "anyone who divorces, then remarries is committing adultery "
    "(as is the person the individual marries)(Matthew 5:32).  "
    "The majority of those who get married wind up divorcing and "
    "remarrying at a later date.  And the vast majority of people "
    "have sexual thoughts about people other than their mates.  "
    "We're now down to very few people, indeed.  But even if you "
    "think you're somehow in the clear, guess again.  Not only are "
    "individuals who marry a second time condemned, but so are "
    "their children, their grandchildren, their great grandchildren,"
    " etc.  Because their second marriage is a nullity, any "
    "children of that marriage are illegitimate and are thus "
    "condemned to the 10th generation (Deuteronomy 23:2).  "
    "In other words, not only must you make sure you do not "
    "engage in any of the sins Paul said would ensure eternity "
    "aflame, you must hope none of your distant ancestors ever "
    "divorced and conceived one of your great, great, great "
    "grandparents out-of-wedlock or during the second (and "
    "unrecognized) marriage.  You see, friends, Heaven is going to "
    "be a very select place, indeed -- more exclusive than even "
    "the best of country clubs.  Now, I know some of you may "
    "find these condemnations a bit disheartening, but you really "
    "shouldn't.  After all, God told us centuries ago that children "
    "would be slaughtered for the sins of their parents (Isaiah "
    "14:21-22).  Plus, these condemned people will be joined "
    "in Hell by individuals who did nothing wrong in their "
    "lives because they had no lives.  God said not only that "
    "we are all born in sin, but that we are conceived in sin "
    "as well (Genesis 5:3; Job 15:14; 25:4; Psalms 51:5).  "
    "In light of that sin, we have no hope of reaching Heaven "
    "unless and until we accept Jesus.  Unfortunately, many "
    "never have that opportunity.  I am, of course, speaking "
    "of all the unborn children who die in the womb or during "
    "delivery, the SIDS children, all the children who die "
    "before they reach the age at which they can understand Jesus, "
    "the mentally retarded who don't have the capacity to "
    "know Jesus, and all those third world residents the "
    "missionaries never reached with the good news of our Lord.  "
    "What a shame that all of these individuals must spend forever "
    "in flames.  Let us pray that Satan takes it easy on them in "
    "the hereafter.  In Jesus' name we pray, Amen. ")
plaintext_bin = list(map(int, text_to_bits(plaintext)))

### Keyword
keyword = "Shane"
keyword_bin = text_to_bits(keyword)

### Keys
key_17 = list(map(int, '1' + keyword_bin[:16]))
key_25 = list(map(int, '1' + keyword_bin[16:]))

### LFSR Plaintext
lfsr_17 = LFSR(plaintext_bin, key_17, (16, 2), [])
lfsr_25 = LFSR(plaintext_bin, key_25, (24, 7, 5, 1), [])

### Full Adder Plaintext
ciphertext_bin = FullAdder(plaintext_bin, lfsr_17, lfsr_25, 0, [])

### Output Ciphertext
ciphertext = text_from_bits("".join(map(str, ciphertext_bin)))

### Full Adder Ciphertext
dectext_bin = FullAdder(ciphertext_bin, lfsr_17, lfsr_25, 0, [])

### Output Dectext
dectext = text_from_bits("".join(map(str, dectext_bin)))

### Print the results
print("The keyword: ", keyword)
print("\nThe plaintext: ", plaintext)
print("\nThe ciphertext: ", ciphertext)
print("\nThe dectext: ", dectext)